services:
  backend:
    build: . 
    container_name: teb-sonati
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate --run-syncdb &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    # restart: always
    volumes:
      - ./:/app 


    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db: 
    image: postgres:15
    # restart : always
    environment:
      POSTGRES_DB: ${DB_POSTGRES}
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES} 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_POSTGRES}"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

