# Generated by Django 5.2.5 on 2025-09-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_info',
            field=models.JSONField(blank=True, null=True, verbose_name='اطلاعات اضافی'),
        ),
    ]
