# Generated by Django 5.2.5 on 2025-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='فواید'),
        ),
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='تاریخچه'),
        ),
        migrations.AddField(
            model_name='product',
            name='precautions',
            field=models.TextField(blank=True, null=True, verbose_name='موارد احتیاط'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='طریقه مصرف'),
        ),
    ]
