# Generated by Django 5.2.5 on 2025-11-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
